Fixes #5269 Several problems with postinstall script's function enforce_redis ()

diff --git a/contrib/packager.io/functions b/contrib/packager.io/functions
--- a/contrib/packager.io/functions
+++ b/contrib/packager.io/functions
@@ -229,9 +229,24 @@ function create_webserver_config () {
 }
 
 function enforce_redis () {
+  REDIS_URL=$(zammad config:get REDIS_URL)
   if [ -n "${REDIS_URL}" ]; then
-    echo "# Redis URL ${REDIS_URL} found."
-    return 0
+    echo "# REDIS_URL variable set to ${REDIS_URL}."
+    REDIS_URL_HOST=$(echo ${REDIS_URL} | awk -F[/:] '{print $4}')
+    REDIS_URL_PORT=$(echo ${REDIS_URL} | awk -F[/:] '{print $5}')
+    nc -z ${REDIS_URL_HOST} ${REDIS_URL_PORT} 2> /dev/null
+
+    if [ $? -eq 0 ]; then
+      echo "# ${REDIS_URL} is reachable."
+      return 0
+    else
+      echo "# ${REDIS_URL} not reachable."
+      echo "ERROR - No redis server found!"
+      echo "Please install Redis following the instructions at https://redis.io/docs/getting-started/ or set the REDIS_URL environment variable with the following command."
+      echo -e "zammad config:set REDIS_URL=redis://your.redis.server:6379\n"
+      echo "Please fix these issues, then run the package installation again."
+      exit 1
+    fi
   fi
 
   echo "# Enforcing Redis..."
@@ -239,6 +254,19 @@ function enforce_redis () {
   local REDIS_SERVICE_NAME=""
   if [ "${OS}" == "DEBIAN" ]; then
       REDIS_SERVICE_NAME="redis-server"
+  elif [ "${OS}" == "SUSE" ]; then
+      REDIS_PID=$(ss -tlpn | grep ':6379' | awk '{print $6}' | grep -oP -m1 '\d+' | head -n1)
+      if [ -z "${REDIS_PID}" ]; then
+        echo -e "ERROR - SUSE Linux detected but no running redis-instance listening on port 6379 or REDIS_URL set.\n"
+        echo "SUSE Linux uses a systemd template for its redis package."
+        echo "If redis was installed via zypper, please make sure an instance of its template-service is running (e.g. redis@zammad.service) and it is listening on port 6379."
+        echo "Alternatively, you can set the REDIS_URL environment variable with the following command."
+        echo -e "zammad config:set REDIS_URL=redis://your.redis.server:6379\n"
+        echo "Please fix these issues, then run the package installation again."
+        exit 1
+      fi
+      REDIS_SERVICE_NAME=$(ps -p $REDIS_PID -o unit=)
+      echo "# Redis service ${REDIS_SERVICE_NAME} detected."
   else
       REDIS_SERVICE_NAME="redis"
   fi
@@ -254,12 +282,6 @@ function enforce_redis () {
       return 0
     fi
   fi
-
-  echo "It seems no redis server runs locally."
-  echo "Please install Redis following the instructions at https://redis.io/docs/getting-started/ or set the REDIS_URL environment variable."
-  echo "e.g. export REDIS_URL=redis://your.redis.server:6379"
-  echo
-  echo "Please try again the Zammad package installation."
 
   return 1
 }
