Add final failing state and some minor improvements.

diff --git a/contrib/packager.io/functions b/contrib/packager.io/functions
--- a/contrib/packager.io/functions
+++ b/contrib/packager.io/functions
@@ -240,7 +240,7 @@ function enforce_redis () {
       return 0
     else
       echo "# Connection check unsuccessful."
-      echo "ERROR - No redis server found."
+      echo "ERROR - No redis server found at ${REDIS_URL}."
       echo "Please install Redis following the instructions at https://redis.io/docs/getting-started/ or set the REDIS_URL environment variable with the following command."
       echo -e "zammad config:set REDIS_URL=redis://your.redis.server:6379\n"
       echo "Please fix these issues, then run the package installation again."
@@ -263,9 +263,10 @@ function enforce_redis () {
         echo -e "zammad config:set REDIS_URL=redis://your.redis.server:6379\n"
         echo "Please fix these issues, then run the package installation again."
         exit 1
+      else
+        REDIS_SERVICE_NAME=$(ps -p $REDIS_PID -o unit=)
+        echo "# Redis service ${REDIS_SERVICE_NAME} detected."
       fi
-      REDIS_SERVICE_NAME=$(ps -p $REDIS_PID -o unit=)
-      echo "# Redis service ${REDIS_SERVICE_NAME} detected."
   else
       REDIS_SERVICE_NAME="redis"
   fi
@@ -275,14 +276,15 @@ function enforce_redis () {
     ${INIT_CMD} enable ${REDIS_SERVICE_NAME}
 
     echo "# Starting Redis server"
-    ${INIT_CMD} restart ${REDIS_SERVICE_NAME}
-    if [ $? -eq 0 ]; then
+    if ${INIT_CMD} restart ${REDIS_SERVICE_NAME}; then
       echo "# Redis server is running."
       return 0
+  else
+      echo -e "\nSomething went wrong. Please check any error output above and fix the issues."
+      echo "Then run the package installation again."
+      exit 1
     fi
   fi
-
-  return 1
 }
 
 function setup_elasticsearch () {
